--DDL DATA DEFINITION LANGUAGE: CREATE, DROP, TRUNCATE, ALTER 
CREATE DATABASE UTCTIENDA1


CREATE TABLE BODEGA
( CODIGO INT PRIMARY KEY IDENTITY (1,1), 
 DESCRIPCION VARCHAR(100) NOT NULL
 

)
--DML DATA MANIPULATION LANGUAGE: SELECT, INSERT DELETE,UPDATE 

INSERT INTO BODEGA (DESCRIPCION) VALUES  ('BODEGA 1'),('BODEGA 3')
INSERT INTO BODEGA (DESCRIPCION) VALUES ('BODEGA 2')

--CONSULTAS REGISTROS 
SELECT CODIGO,DESCRIPCION FROM BODEGA 
SELECT * FROM BODEGA
SELECT DESCRIPCION  FROM BODEGA

--TCL TRANSACTION CONTROL LANGUAGE: REVOKE, GRANT.

