 


 CREATE DATABASE UNVERSIDADUTC
 


 USE UNVERSIDADUTC
 
 --CREAR TABLA ESTUDIANTE,CURSO, ESTUDIANTECURSO
 
 CREATE TABLE ESTUDIANTE
 (
 CEDULA VARCHAR (12) PRIMARY KEY, 
 NOMBRE VARCHAR (50) NOT NULL, 
 EDAD INT 
 )
 
 CREATE TABLE CURSO 
 (
 CODIGO INT PRIMARY KEY IDENTITY(1,1),
 NOMBRE VARCHAR(50) NOT NULL, 
 )

 CREATE TABLE ESTUDIANTECURSO 
 (
 CEDULA_ESTUDIANTE VARCHAR (12) FOREIGN KEY REFERENCES ESTUDIANTE (CEDULA), 
 CODIGO_CURSO INT FOREIGN KEY REFERENCES CURSO (CODIGO), 
 HORARIO DATE 

 )